app:
  datasource:
    driver: mysql
    host: localhost
    port: 3306
    database: todo-list
    username: root
    password: 123456
    migrationSource: file://migrations
  logging:
    development: true