version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: lean_go
    environment:
      MYSQL_DATABASE: todo-list
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
